### ISSUE TITLE
[$50] Heroku memory quota

### ISSUE THREAD

**Issue by gondzo** [topcoderinc/dsp-frontend#15] opened 2016-12-28 12:49 UTC
Heroku logs show frequent restarts due to 
```
Process running mem=530M(103.6%)8:13 PM
Error R14 (Memory quota exceeded)
```
Running the process locally requires < 100MB

**Comment by chqy24** [comment] 2016-12-28 13:16
I will take this one, how can I assign it to myself?
handle: ouyangki

**Comment by chqy24** [comment] 2016-12-28 13:25
I've already limit the memory to 512M in previous challenge, and I will try to reproduce this memory overflow issue.

**Comment by chqy24** [comment] 2016-12-28 13:51
@gondzo, can you provider more info about the issue, which branch and all the environment variable value

**Comment by gondzo** [comment] 2016-12-28 13:59
@chqy24 
both dev and master branch, environment is the same as in .env.example

**Comment by chqy24** [comment] 2016-12-28 14:15
@gondzo, in the script of "heroku:dev:init", I set a environment variable NODE_ENV=development, which will enable hot module update for local develop, in fact this might be useless in a heroku app.
How do you think if I disable that 'hot module update' feature in dev of heroku by setting NODE_ENV to another value like 'dev'?

**Comment by gondzo** [comment] 2016-12-28 14:21
Yes, disabling hot module replacement is ok. You can even change it to production as that's what makes most sense for a heroku app

**Comment by chqy24** [comment] 2016-12-28 15:05
Although I think this issue is caused by that 'hot module update' feature, I also reduce the limitation for both of 'npm run build' and 'npm run start' to 384M, you can adjust the value in 'package.json' according to your need. FYI, a limitation of 256M for 'npm run build' will be failed according to my test.

I already create a PR [here](https://github.com/topcoderinc/dsp-frontend/pull/16)

**Closed as completed** 2016-12-30 23:02 UTC
Labels: Payment Required

**Comment by kbowerma** [comment] 2017-02-01 16:24
payment record created DRONESERIES-8
